#!/bin/bash
#
# Install Grail into the GemDB database.
#
# This is GemDB's own installer, not Grail's ./install_base.sh + ./install.sh.
# The difference is one step: Grail's scripts compile the CPython shim from
# source, which needs a C toolchain and the engine's headers. GemDB ships that
# library prebuilt inside the extension, so the compile is skipped and a new
# developer needs no compiler at all. Everything else below is the same
# sequence of topaz scripts Grail's own installers run, in the same order.
#
# Required environment:
#   GRAIL_DIR            staged Grail checkout (also the working directory)
#   GEMSTONE             engine product directory
#   GEMSTONE_GLOBAL_DIR  engine global directory
#   GEMDB_STONE          stone name
#   GEMDB_USER           login user for the per-user install
#   GEMDB_PASSWORD       that user's password
#   SHIM_LIB_PATH        prebuilt CPython shim (empty to install without it)
#   PYTHON_PACKAGE_PATH  Grail's Python package root
#
set -euo pipefail

: "${GRAIL_DIR:?GRAIL_DIR is not set}"
: "${GEMSTONE:?GEMSTONE is not set}"
: "${GEMDB_STONE:?GEMDB_STONE is not set}"
: "${GEMDB_USER:?GEMDB_USER is not set}"
: "${GEMDB_PASSWORD:?GEMDB_PASSWORD is not set}"

export PATH="$GEMSTONE/bin:$PATH"
cd "$GRAIL_DIR"

if ! command -v topaz >/dev/null 2>&1; then
    echo "ERROR: topaz is not on PATH (looked in $GEMSTONE/bin)." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Topaz session defaults.
# ---------------------------------------------------------------------------
# Grail's install scripts deliberately do NOT hardcode a user or stone: they
# read both from ./.topazini, so that the same scripts can install a per-user
# Grail for whoever is running them. GemDB writes that file to point at its own
# single database.
cat > "$GRAIL_DIR/.topazini" <<EOF
! Written by GemDB. Edit gemdb settings rather than this file.
set user $GEMDB_USER pass $GEMDB_PASSWORD
set gemstone $GEMDB_STONE
EOF

GS_VERSION=$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' "$GEMSTONE/version.txt" 2>/dev/null | head -1 || true)
echo "Database engine version: ${GS_VERSION:-unknown}"

run_topaz() {
    local script="$1"
    if [ ! -f "$script" ]; then
        echo "ERROR: expected Grail script is missing: $script" >&2
        exit 1
    fi
    echo "--- topaz $script"
    LC_ALL=C topaz -lq -S "$script" < /dev/null
}

# ---------------------------------------------------------------------------
# Step 1: the shared base, installed once per database as SystemUser.
# ---------------------------------------------------------------------------
# What belongs in the base depends on the engine version, and the split has to
# match what step 3 files per-user -- whatever is not filed here must be filed
# there. 3.7.x is published and cannot be fixed in its base image, so it needs
# the session-method policy patch and the shared kernel extensions; 4.0+ has
# both natively and takes only the Unicode setting.
echo "== Installing the shared Grail base"
case "$GS_VERSION" in
    3.7.*)
        run_topaz scripts/session_methods_env1_base_37.gs
        ./scripts/setUnicodeMode.sh
        run_topaz scripts/install_base37.gs
        ;;
    *)
        ./scripts/setUnicodeMode.sh
        ;;
esac
run_topaz scripts/set_base_marker.gs

# ---------------------------------------------------------------------------
# Step 2: the generated include that step 3 files in.
# ---------------------------------------------------------------------------
# install.gs unconditionally reads out/gen/kernel_class_extensions.gs. On 3.7.x
# the base above already filed those methods as SystemUser, so the include is
# empty; on 4.0+ they are filed here as per-user session methods.
mkdir -p "$GRAIL_DIR/out/gen"
{
    echo "! GENERATED by GemDB -- do not edit."
    echo "! Detected engine ${GS_VERSION:-unknown}."
    case "$GS_VERSION" in
        3.7.*) echo "! 3.7.x: kernel extensions were filed by the shared base above." ;;
        *)     echo "input ./scripts/install_base40.gs" ;;
    esac
} > "$GRAIL_DIR/out/gen/kernel_class_extensions.gs"

# ---------------------------------------------------------------------------
# Step 3: the per-user install.
# ---------------------------------------------------------------------------
# install.gs reads SHIM_LIB_PATH from the session environment and records it in
# the database, so every later session finds the shim without the variable
# being set again. That recorded path is why GemDB stages Grail to a stable
# directory instead of running it from inside the extension.
export SHIM_LIB_PATH="${SHIM_LIB_PATH:-}"
export PYTHON_PACKAGE_PATH="${PYTHON_PACKAGE_PATH:-$GRAIL_DIR/src/python}"
export GRAIL_DIR

if [ -n "$SHIM_LIB_PATH" ] && [ ! -f "$SHIM_LIB_PATH" ]; then
    echo "WARNING: no prebuilt CPython shim at $SHIM_LIB_PATH." >&2
    echo "         Grail will install, but C extension modules will not be available." >&2
    export SHIM_LIB_PATH=""
fi

echo "== Installing Grail as $GEMDB_USER"
rm -f "$GRAIL_DIR"/*.out
run_topaz src/smalltalk/install.gs

# ---------------------------------------------------------------------------
# Step 4: deploy the gemdb module.
# ---------------------------------------------------------------------------
# One cold import, committed. This is what makes a fresh session's
# `import gemdb` leave nothing to commit — the module and its warmed
# function caches become committed state — which gemdb's transaction()
# entry check depends on (Grail docs/GemDB_Module.md, session hygiene).
# The other half of the contract is per-session: every session must enable
# canonical modules to warm-bind what this deploys (session.ts and
# gemdb-run.tpz both do). Guarded: a Grail payload from before the gemdb
# module simply has no script, and the install is still complete.
if [ -f scripts/deployGemdb.gs ]; then
    echo "== Deploying gemdb"
    run_topaz scripts/deployGemdb.gs
else
    echo "NOTE: this Grail payload predates gemdb (no scripts/deployGemdb.gs); skipping its deploy."
fi

echo "== Grail installed"
