import * as fs from 'fs';
import * as path from 'path';
import { DB_PASSWORD, DB_USER, PINNED_ENGINE_VERSION, STONE_NAME, rootPath } from './config';
import { log } from './log';
import { enginePath, grailPath } from './paths';
import { sharedLibraryExtension } from './platform';

/**
 * The `gemdb` shell command: CPython's command line, backed by the database.
 *
 *   gemdb hello.py        like python3 hello.py
 *   gemdb -m some.module  like python3 -m some.module
 *   gemdb -c 'print(1)'   like python3 -c
 *   gemdb                 a REPL (Grail's own topaz REPL)
 *
 * Three generated files under `<rootPath>/bin`, rewritten on every staging so
 * they always match the installed engine and the staged Grail:
 *
 *   `gemdb`            the wrapper. Sets the whole engine environment itself,
 *                      so it works from any shell with no setup beyond PATH.
 *   `gemdb-run.tpz`    the topaz driver for running a file or module.
 *   `gemdb-repl.tpz`   credentials + a handoff to Grail's interactive REPL.
 *
 * It drives *linked* topaz — the right login for a CLI: its own process, one
 * session, crash isolation by construction, and real stdin/stdout. (The REPL
 * and notebooks inside the editor stay RPC for exactly the opposite reasons.)
 *
 * Exit codes are the part that took working out, so it is recorded here:
 * topaz does not translate a gem-side `ExitClientError status:` into a process
 * exit status from a `run` block, and its `iferr … exit 1` action exits 0.
 * The only reliable carrier found was a plain `exit <n>` script line — so the
 * driver instead reports the status through a file named in GEMDB_STATUS_FILE,
 * and the wrapper turns that into the process exit code. The status file is
 * passed by environment variable, not argument, so the user's argv reaches
 * their program untouched.
 *
 * Known gaps against CPython, all measured: an uncaught `sys.exit(n)` exits 1
 * rather than n (Grail surfaces SystemExit without the status), and `input()`
 * fails in the current Grail build (`System stdin` is not understood). Both
 * are upstream; the wrapper is where they will start working when fixed.
 */

export function cliDirPath(): string {
  return path.join(rootPath(), 'bin');
}

export function cliPath(): string {
  return path.join(cliDirPath(), 'gemdb');
}

const TOPAZ_TUNING = `-T 400000 -C 'GEM_TEMPOBJ_CODE_SIZE=300000;'`;

export function writeCliScripts(): void {
  const engine = enginePath();
  if (!engine) throw new Error('The database engine is not installed.');
  const root = rootPath();
  const grail = grailPath();

  fs.mkdirSync(cliDirPath(), { recursive: true });

  // The topaz driver for one file or module. `set` lines beat any ~/.topazini
  // (the ini runs first, these run later), so a Jasper user's defaults cannot
  // hijack the login. Errors are caught as AbstractException, not Error —
  // Grail's Python exceptions live outside the Error branch, which is why
  // grail.tpz's own file mode exits 0 on a Python error.
  fs.writeFileSync(
    path.join(cliDirPath(), 'gemdb-run.tpz'),
    `! Generated by GemDB. Regenerated on every update — do not edit.
set user ${DB_USER} pass ${DB_PASSWORD}
set gemstone ${STONE_NAME}
login
run
| args ofs target prior status statusFile |
args := System commandLineArguments.
1 to: args size do: [:j | (args at: j) = '--' ifTrue: [ofs := j]].
statusFile := System gemEnvironmentVariable: 'GEMDB_STATUS_FILE'.
status := 0.
prior := Transcript.
[
    Transcript := GsFile stdout.
    [
        target := args at: ofs + 1.
        target = '-m'
            ifTrue: [importlib runModule: (args at: ofs + 2)]
            ifFalse: [importlib runPath: target].
    ] on: AbstractException do: [:ex |
        (ex isKindOf: ExitClientError)
            ifTrue: [status := ex status ifNil: [1]]
            ifFalse: [
                | msg |
                msg := ex messageText ifNil: [ex description].
                GsFile stdout flush.
                GsFile stderr nextPutAll: msg; lf; flush.
                status := 1].
    ].
] ensure: [
    Transcript := prior.
    statusFile ifNotNil: [
        | f |
        f := GsFile openWrite: statusFile.
        f nextPutAll: status printString; close].
].
%
exit 0
`,
  );

  // Interactive mode: credentials, then Grail's own REPL, verbatim.
  fs.writeFileSync(
    path.join(cliDirPath(), 'gemdb-repl.tpz'),
    `! Generated by GemDB. Regenerated on every update — do not edit.
set user ${DB_USER} pass ${DB_PASSWORD}
set gemstone ${STONE_NAME}
input ${path.join(grail, 'scripts', 'grail.tpz')}
`,
  );

  const script = `#!/bin/bash
# gemdb — run Python inside the GemDB database, from any shell.
# Generated by the GemDB extension; regenerated on every update. Do not edit.
#
#   gemdb file.py [args]     run a file            gemdb -m pkg.mod   run a module
#   gemdb -c 'code'          run a string          gemdb              open a REPL
#
# Put this on your PATH:   export PATH="\${HOME}/GemDB/bin:$PATH"

set -u

ROOT="${root}"
GEMSTONE="${engine}"
GRAIL_DIR="${grail}"
STONE="${STONE_NAME}"

export GEMSTONE
export GEMSTONE_GLOBAL_DIR="$ROOT"
export GEMSTONE_SYS_CONF="$ROOT/db/conf"
export GEMSTONE_EXE_CONF="$ROOT/db/conf"
export GRAIL_DIR
export PYTHON_PACKAGE_PATH="$GRAIL_DIR/src/python"
export SHIM_LIB_PATH="$GRAIL_DIR/src/c/shim/libcpython_ua.${sharedLibraryExtension()}"
export PATH="$GEMSTONE/bin:$PATH"

usage() {
  sed -n '4,7p' "$0" | sed 's/^# *//'
}

case "\${1:-}" in
  -h|--help) usage; exit 0 ;;
  -V|--version)
    echo "GemDB Python ($(sed -n 's/^grail=//p' "$GRAIL_DIR/GRAIL_VERSION" 2>/dev/null || echo unknown), engine ${PINNED_ENGINE_VERSION})"
    exit 0 ;;
esac

# The database must be up — a linked gem still needs the stone. Starting it
# here is the same judgement the editor makes: running Python is the request.
if ! "$GEMSTONE/bin/gslist" 2>/dev/null | awk -v s="$STONE" '$(NF-1) == "Stone" && $NF == s { found = 1 } END { exit !found }'; then
  echo "gemdb: starting the database…" >&2
  if ! "$GEMSTONE/bin/startstone" -l "$ROOT/db/log/$STONE.log" "$STONE" >/dev/null 2>&1; then
    echo "gemdb: the database at $ROOT could not be started. See $ROOT/db/log/$STONE.log" >&2
    exit 1
  fi
fi

# No arguments: the interactive REPL, on the user's own terminal.
if [ "$#" -eq 0 ]; then
  exec topaz -L -q -S "$ROOT/bin/gemdb-repl.tpz" ${TOPAZ_TUNING} --
fi

# -c 'code': materialise the code as a file, like CPython's -c but visibly so.
# mktemp is given an explicit template — BSD and GNU disagree about -t.
CODE_FILE=""
if [ "$1" = "-c" ]; then
  [ "$#" -ge 2 ] || { echo "gemdb: -c requires an argument" >&2; exit 2; }
  CODE_FILE="$(mktemp "\${TMPDIR:-/tmp}/gemdb-c-XXXXXX").py"
  printf '%s\\n' "$2" > "$CODE_FILE"
  shift 2
  set -- "$CODE_FILE" "$@"
fi

# A file that is not there should fail here, with a message and exit code
# shaped like CPython's, not as a Smalltalk stack.
if [ "$1" != "-m" ] && [ ! -e "$1" ]; then
  echo "gemdb: can't open file '$1': No such file or directory" >&2
  exit 2
fi

# topaz cannot carry an exit status out of a run block, so the driver writes
# it to a file and this wrapper becomes the exit code. See gemdb-run.tpz.
GEMDB_STATUS_FILE="$(mktemp "\${TMPDIR:-/tmp}/gemdb-status-XXXXXX")"
export GEMDB_STATUS_FILE
topaz -L -q -S "$ROOT/bin/gemdb-run.tpz" ${TOPAZ_TUNING} -- "$@"
RC=$?
STATUS="$(cat "$GEMDB_STATUS_FILE" 2>/dev/null || true)"
rm -f "$GEMDB_STATUS_FILE"
[ -n "$CODE_FILE" ] && rm -f "$CODE_FILE" "\${CODE_FILE%.py}"
case "$STATUS" in
  ''|*[!0-9]*) [ "$RC" -ne 0 ] && exit "$RC"; exit 1 ;;
  *) exit "$STATUS" ;;
esac
`;

  fs.writeFileSync(cliPath(), script);
  fs.chmodSync(cliPath(), 0o755);
  log(`Wrote the gemdb command to ${cliPath()}`);
}
